version: "2"
services:
  registry:
    build: ./registry-service
    networks:
      - shorty
    ports:
      - "1111:1111"
  user:
    build: ./user-service
    networks:
      - shorty
  short-link:
    build: ./short-link-service
    networks:
      - shorty
  user-shortlink:
    build: ./user-shortlink-service
    networks:
      - shorty
  frontend:
    build: ./frontend-service
    networks:
      - shorty
    ports:
      - "8080:8080"
  monitoring:
    build: ./monitoring-service
    networks:
      - shorty
    ports:
      - "9999:9999"
networks:
  shorty: