# Spring properties
spring:
  application:
    name: frontend-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# API Proxy configuration
zuul:
  host:
    connect-timeout-millis: 300000
    socket-timeout-millis: 600000
  routes:
    short-link-service:
      path: /shortLinks/**
      serviceId: short-link-service
      stripPrefix: false
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    user-shortlink-service:
      path: /userShortLink/**
      serviceId: user-shortlink-service
      stripPrefix: false

#resolve the service time-out exception
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000


# Service Monitoring
turbine:
  clusterNameExpression: new String("default")
  appConfig: frontend-service