# Spring properties
spring:
  application:
    name: frontend-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# API Proxy configuration
zuul:
  routes:
    short-link-service:
      path: /shortlinks/**
      serviceId: short-link-service
      stripPrefix: false
